name          'chriscowley-ovirtagent'
version       '0.1.0'
source        'https://github.com/chriscowley/chriscowley-ovirtagent.git'
author        'chriscowley'
license       'Apache 2.0'
summary       'Installs the oVirt guest tools'
description   'Installs the oVirt guest tools'
project_page  'https://github.com/chriscowley/chriscowley-ovirtagent'

dependency 'puppetlabs/stdlib'
